version: "3"
services:
  app:
    build: .
    ports:
      - "50001:5000"
    container_name: app
    volumes:
      - ./app:/usr/src/app
    command: flask run --host=0.0.0.0
      
  db:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    volumes:
      - "./mariadb:/var/lib/mariadb"
      - "./initdb.d:/docker-entrypoint-initdb.d"
    environment:
      MARIADB_DATABASE: first_database
      MARIADB_USER: username
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: password
